version: '3.8'

networks:
  mimiposstoreApp:

services:
  miniPosStoreDB:
    container_name: MiniPosStoreDB
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "8002:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Sa123456!
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - mimiposstoreApp

  mimiposstore:
    container_name: mimiposstore
    build:
      context: .
      dockerfile: MimiPosStore/Dockerfile
    image: mimiposstore
    ports:
      - "80:80"
    depends_on:
      - miniPosStoreDB
    environment:
      - DB_HOST=miniPosStoreDB
      - DB_Name=MiniPosStore
      - DB_SA_PASSWORD=Sa123456!
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ./MimiPosStore/wwwroot:/app/wwwroot
    networks:
      - mimiposstoreApp

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - "9000:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - mimiposstoreApp

volumes:
  sql_data:
  app_wwwroot:
  portainer_data:
